// <auto-generated />
using System;
using APIDoctorCheckUp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIDoctorCheckUp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.AlertThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailuresDown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseTimeCriticalMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3000);

                    b.Property<int>("ResponseTimeWarningMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1000);

                    b.HasKey("Id");

                    b.HasIndex("EndpointId")
                        .IsUnique();

                    b.ToTable("AlertThresholds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsecutiveFailuresDown = 3,
                            EndpointId = 1,
                            ResponseTimeCriticalMs = 3000,
                            ResponseTimeWarningMs = 1000
                        },
                        new
                        {
                            Id = 2,
                            ConsecutiveFailuresDown = 3,
                            EndpointId = 2,
                            ResponseTimeCriticalMs = 3000,
                            ResponseTimeWarningMs = 1000
                        },
                        new
                        {
                            Id = 3,
                            ConsecutiveFailuresDown = 3,
                            EndpointId = 3,
                            ResponseTimeCriticalMs = 3000,
                            ResponseTimeWarningMs = 1000
                        },
                        new
                        {
                            Id = 4,
                            ConsecutiveFailuresDown = 3,
                            EndpointId = 4,
                            ResponseTimeCriticalMs = 3000,
                            ResponseTimeWarningMs = 1000
                        },
                        new
                        {
                            Id = 5,
                            ConsecutiveFailuresDown = 3,
                            EndpointId = 5,
                            ResponseTimeCriticalMs = 3000,
                            ResponseTimeWarningMs = 1000
                        },
                        new
                        {
                            Id = 6,
                            ConsecutiveFailuresDown = 3,
                            EndpointId = 6,
                            ResponseTimeCriticalMs = 3000,
                            ResponseTimeWarningMs = 1000
                        });
                });

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.CheckResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId", "CheckedAt");

                    b.ToTable("CheckResults");
                });

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId", "ResolvedAt");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.MonitoredEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(60);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedStatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(200);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonitoredEndpoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIntervalSeconds = 60,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = "Unknown",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            Name = "HTTPBin GET",
                            Url = "https://httpbin.org/get"
                        },
                        new
                        {
                            Id = 2,
                            CheckIntervalSeconds = 60,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = "Unknown",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            Name = "JSONPlaceholder Post",
                            Url = "https://jsonplaceholder.typicode.com/posts/1"
                        },
                        new
                        {
                            Id = 3,
                            CheckIntervalSeconds = 120,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = "Unknown",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            Name = "GitHub API",
                            Url = "https://api.github.com"
                        },
                        new
                        {
                            Id = 4,
                            CheckIntervalSeconds = 120,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = "Unknown",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            Name = "Cat Fact",
                            Url = "https://catfact.ninja/fact"
                        },
                        new
                        {
                            Id = 5,
                            CheckIntervalSeconds = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = "Unknown",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            Name = "Snippet Vault API",
                            Url = "https://snippetvault.onrender.com/health"
                        },
                        new
                        {
                            Id = 6,
                            CheckIntervalSeconds = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatus = "Unknown",
                            ExpectedStatusCode = 200,
                            IsActive = true,
                            Name = "JSON to C# Generator API",
                            Url = "https://jsontocsharp.onrender.com/health"
                        });
                });

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.AlertThreshold", b =>
                {
                    b.HasOne("APIDoctorCheckUp.Domain.Entities.MonitoredEndpoint", "Endpoint")
                        .WithOne("AlertThreshold")
                        .HasForeignKey("APIDoctorCheckUp.Domain.Entities.AlertThreshold", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.CheckResult", b =>
                {
                    b.HasOne("APIDoctorCheckUp.Domain.Entities.MonitoredEndpoint", "Endpoint")
                        .WithMany("CheckResults")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.Incident", b =>
                {
                    b.HasOne("APIDoctorCheckUp.Domain.Entities.MonitoredEndpoint", "Endpoint")
                        .WithMany("Incidents")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("APIDoctorCheckUp.Domain.Entities.MonitoredEndpoint", b =>
                {
                    b.Navigation("AlertThreshold");

                    b.Navigation("CheckResults");

                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
